#define OAUTH_2_AUTH "https://www.dropbox.com/1/oauth2/authorize"
#define OAUTH_2_TOKEN "https://api.dropbox.com/1/oauth2/token"
#define ACCOUNT_INFO "https://api.dropbox.com/1/account/info"
#define FILES_GET "https://api-content.dropbox.com/1/files/dropbox"
#define FILES_PUT "https://api-content.dropbox.com/1/files_put/dropbox"
#define METADATA "https://api.dropbox.com/1/metadata/dropbox"
#define DELTA	"https://api.dropbox.com/1/delta"
#define LONGPOLL "https://api-notify.dropbox.com/1/longpoll_delta"
